<?php
$dogBreeds = [
    "Affenpinscher", "Afghan Hound", "Airedale Terrier", "Akita", "Alaskan Malamute",
    "American Bulldog", "American Eskimo Dog", "American Foxhound", "American Pit Bull Terrier",
    "American Staffordshire Terrier", "Australian Cattle Dog", "Australian Shepherd",
    "Australian Terrier", "Basenji", "Basset Hound", "Beagle", "Bearded Collie",
    "Bedlington Terrier", "Belgian Malinois", "Bernese Mountain Dog", "Bichon Frise",
    "Black and Tan Coonhound", "Bloodhound", "Border Collie", "Border Terrier", "Borzoi",
    "Boston Terrier", "Bouvier des Flandres", "Boxer", "Boykin Spaniel", "Briard",
    "Brittany", "Brussels Griffon", "Bull Terrier", "Bulldog", "Bullmastiff", "Cairn Terrier",
    "Canaan Dog", "Cane Corso", "Cardigan Welsh Corgi", "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever", "Chihuahua", "Chinese Crested", "Chinese Shar-Pei",
    "Chow Chow", "Clumber Spaniel", "Cocker Spaniel", "Collie", "Curly-Coated Retriever",
    "Dachshund", "Dalmatian", "Doberman Pinscher", "English Cocker Spaniel",
    "English Setter", "English Springer Spaniel", "English Toy Spaniel", "Entlebucher Mountain Dog",
    "Field Spaniel", "Finnish Spitz", "Flat-Coated Retriever", "French Bulldog",
    "German Pinscher", "German Shepherd Dog", "German Shorthaired Pointer",
    "German Wirehaired Pointer", "Giant Schnauzer", "Glen of Imaal Terrier",
    "Golden Retriever", "Gordon Setter", "Great Dane", "Great Pyrenees", "Greater Swiss Mountain Dog",
    "Greyhound", "Havanese", "Ibizan Hound", "Irish Setter", "Irish Terrier",
    "Irish Water Spaniel", "Irish Wolfhound", "Italian Greyhound", "Japanese Chin",
    "Keeshond", "Kerry Blue Terrier", "Komondor", "Kuvasz", "Labrador Retriever",
    "Lakeland Terrier", "Leonberger", "Lhasa Apso", "Lowchen", "Maltese", "Manchester Terrier",
    "Mastiff", "Miniature Bull Terrier", "Miniature Pinscher", "Miniature Schnauzer",
    "Neapolitan Mastiff", "Newfoundland", "Norfolk Terrier", "Norwegian Elkhound",
    "Norwich Terrier", "Nova Scotia Duck Tolling Retriever", "Old English Sheepdog",
    "Otterhound", "Papillon", "Parson Russell Terrier", "Pekingese", "Pembroke Welsh Corgi",
    "Petit Basset Griffon Vendeen", "Pharaoh Hound", "Plott", "Pointer", "Polish Lowland Sheepdog",
    "Pomeranian", "Poodle", "Portuguese Water Dog", "Pug", "Puli", "Rhodesian Ridgeback",
    "Rottweiler", "Saint Bernard", "Saluki", "Samoyed", "Schipperke", "Scottish Deerhound",
    "Scottish Terrier", "Sealyham Terrier", "Shetland Sheepdog", "Shiba Inu", "Shih Tzu",
    "Siberian Husky", "Silky Terrier", "Skye Terrier", "Smooth Fox Terrier", "Soft Coated Wheaten Terrier",
    "Spinone Italiano", "Staffordshire Bull Terrier", "Standard Schnauzer", "Sussex Spaniel",
    "Swedish Vallhund", "Tibetan Mastiff", "Tibetan Spaniel", "Tibetan Terrier", "Toy Fox Terrier",
    "Vizsla", "Weimaraner", "Welsh Springer Spaniel", "Welsh Terrier", "West Highland White Terrier",
    "Whippet", "Wire Fox Terrier", "Wirehaired Pointing Griffon", "Yorkshire Terrier"
];